// eslint-disable-next-line import/no-anonymous-default-export
export default {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  INCREMENT_ASYNC: "INCREMENT_ASYNC",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  LOGIN_FAIL: "LOGIN_FAIL",

  USER_DATA_REQUEST: "USER_DATA_REQUEST",
  USER_DATA_SUCCESS: "USER_DATA_SUCCESS",
  USER_DATA_FAIL: "USER_DATA_FAIL",
};
